# Име на приложението
spring.application.name=medical-records-system

# MySQL връзка
spring.datasource.url=jdbc:mysql://localhost:3306/medical_records_system
spring.datasource.username=root
spring.datasource.password=root1234

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate настройки
spring.jpa.hibernate.ddl-auto=update

# Показване на SQL заявки в конзолата
spring.jpa.show-sql=true

# Форматиране на SQL заявките
spring.jpa.properties.hibernate.format_sql=true

# MySQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger/OpenAPI (по желание по-късно)
springdoc.api-docs.enabled=true